#ifndef MOTOR_CONFIG_H_
#define MOTOR_CONFIG_H_

#define MOTOR1_PIN   GPIOB,12
#define MOTOR2_PIN   GPIOB,13
#define MOTOR3_PIN   GPIOB,14
#define MOTOR4_PIN   GPIOB,15

#define PWM_FREQUENCY 1000 // 1KHz
#define PWM_MAX_DUTY_CYCLE 100

#endif
